$defs:
  ClaimConfig:
    properties:
      earlyClaim:
        $ref: '#/$defs/ClaimPreferences'
        default:
          character: []
          minKakera: 10000
          series: []
      lateClaim:
        $ref: '#/$defs/ClaimPreferences'
        default:
          character: []
          minKakera: 10000
          series: []
      snipe:
        $ref: '#/$defs/ClaimPreferences'
        default:
          character: []
          minKakera: 10000
          series: []
    title: ClaimConfig
    type: object
  ClaimPreferences:
    properties:
      character:
        default: []
        items:
          type: string
        title: Character
        type: array
      minKakera:
        default: 10000
        title: Minkakera
        type: integer
      series:
        default: []
        items:
          type: string
        title: Series
        type: array
    title: ClaimPreferences
    type: object
  DiscordConfig:
    properties:
      channelId:
        title: Channelid
        type: integer
      mudaeBotId:
        title: Mudaebotid
        type: integer
      token:
        title: Token
        type: string
    required:
    - token
    - channelId
    - mudaeBotId
    title: DiscordConfig
    type: object
  MudaeConfig:
    properties:
      claim:
        $ref: '#/$defs/ClaimConfig'
      roll:
        $ref: '#/$defs/RollConfig'
    required:
    - roll
    - claim
    title: MudaeConfig
    type: object
  RollConfig:
    properties:
      command:
        const: $wg
        title: Command
        type: string
    required:
    - command
    title: RollConfig
    type: object
properties:
  discord:
    $ref: '#/$defs/DiscordConfig'
  mudae:
    $ref: '#/$defs/MudaeConfig'
  name:
    title: Name
    type: string
  version:
    const: 1
    title: Version
    type: integer
required:
- name
- version
- discord
- mudae
title: Config
type: object
