# yaml-language-server: $schema=schema.yaml
name: Example Configuration
version: 1
discord:
  token: ""
  channelId: 0
  mudaeBotId: 432610292342587392
mudae:
  roll:
    command: $w
    doNotRollWhenCannotClaim: True
    doNotRollWhenCannotKakeraReact: False
    rollResetMinuteOffset: 0
  kakeraReact:
    doNotReactToKakeraTypes:
      - kakera
    doNotReactToKakeraTypeIfKakeraPowerLessThan:
      kakeraT: 100
  claim:
    snipe:
      # Snipe my wishes, Nilou, and characters from Wuthering Waves
      wish: True
      character:
        - Nilou
      series:
        - Wuthering Waves
    earlyClaim:
      # If next hour is not reset yet,
      # but there is a roll that meet this criteria (more or equal to 150 kakera)
      # after rolling complete, claim it
      # except if its a character from One Piece
      minKakera: 150
      exception:
        series:
          - One Piece
    lateClaim:
      # If next hour is reset, after rolling complete,
      # claim a roll with the highest kakera value above or equal to 40
      minKakera: 40
