# yaml-language-server: $schema=schema.yaml
name: Example Configuration
version: 1
discord:
  token: ""
  channelId: 0
  mudaeBotId: 432610292342587392
mudae:
  roll:
    command: $w
    doNotRollWhenCanotClaim: True
    doNotRollWhenCannotKakeraReact: False
    rollResetMinuteOffset: 0
  kakeraReact:
    doNotReactToKakeraTypes:
      - kakera
    doNotReactToKakeraTypeIfKakeraPowerLessThan:
      kakeraT: 100
  claim:
    snipe:
      wish: True
      character:
        - Nilou
      series:
        - Wuthering Waves
    earlyClaim:
      minKakera: 150
    lateClaim:
      minKakera: 40
