$defs:
  ClaimConfig:
    properties:
      earlyClaim:
        $ref: '#/$defs/ClaimCriteria'
        default:
          character: []
          minKakera: 10000
          series: []
          wish: false
      lateClaim:
        $ref: '#/$defs/ClaimCriteria'
        default:
          character: []
          minKakera: 10000
          series: []
          wish: false
      snipe:
        $ref: '#/$defs/ClaimCriteria'
        default:
          character: []
          minKakera: 10000
          series: []
          wish: false
    title: ClaimConfig
    type: object
  ClaimCriteria:
    properties:
      character:
        items:
          type: string
        title: Character
        type: array
      minKakera:
        default: 10000
        title: Minkakera
        type: integer
      series:
        items:
          type: string
        title: Series
        type: array
      wish:
        default: false
        title: Wish
        type: boolean
    title: ClaimCriteria
    type: object
  DiscordConfig:
    properties:
      channelId:
        title: Channelid
        type: integer
      mudaeBotId:
        title: Mudaebotid
        type: integer
      token:
        title: Token
        type: string
    required:
    - token
    - channelId
    - mudaeBotId
    title: DiscordConfig
    type: object
  KakeraReactConfig:
    properties:
      doNotReactToKakeraTypeIfKakeraPowerLessThan:
        additionalProperties:
          type: integer
        title: Donotreacttokakeratypeifkakerapowerlessthan
        type: object
      doNotReactToKakeraTypes:
        items:
          type: string
        title: Donotreacttokakeratypes
        type: array
    title: KakeraReactConfig
    type: object
  MudaeConfig:
    properties:
      claim:
        $ref: '#/$defs/ClaimConfig'
        default:
          earlyClaim:
            character: []
            minKakera: 10000
            series: []
            wish: false
          lateClaim:
            character: []
            minKakera: 10000
            series: []
            wish: false
          snipe:
            character: []
            minKakera: 10000
            series: []
            wish: false
      kakeraReact:
        $ref: '#/$defs/KakeraReactConfig'
        default:
          doNotReactToKakeraTypeIfKakeraPowerLessThan: {}
          doNotReactToKakeraTypes: []
      roll:
        $ref: '#/$defs/RollConfig'
        default:
          command: $w
          doNotRollWhenCannotKakeraReact: false
          doNotRollWhenCanotClaim: true
          rollResetMinuteOffset: 0
    title: MudaeConfig
    type: object
  RollConfig:
    properties:
      command:
        default: $w
        enum:
        - $wg
        - $wa
        - $w
        title: Command
        type: string
      doNotRollWhenCannotKakeraReact:
        default: false
        title: Donotrollwhencannotkakerareact
        type: boolean
      doNotRollWhenCanotClaim:
        default: true
        title: Donotrollwhencanotclaim
        type: boolean
      rollResetMinuteOffset:
        default: 0
        title: Rollresetminuteoffset
        type: integer
    title: RollConfig
    type: object
additionalProperties: false
properties:
  discord:
    $ref: '#/$defs/DiscordConfig'
  mudae:
    $ref: '#/$defs/MudaeConfig'
  name:
    title: Name
    type: string
  version:
    const: 1
    title: Version
    type: integer
required:
- name
- version
- discord
- mudae
title: Config
type: object
