$defs:
  ClaimConfig:
    properties:
      earlyClaim:
        $ref: '#/$defs/ClaimCriteria'
      lateClaim:
        $ref: '#/$defs/ClaimCriteria'
      snipe:
        $ref: '#/$defs/ClaimCriteria'
    title: ClaimConfig
    type: object
  ClaimCriteria:
    properties:
      character:
        items:
          type: string
        title: Character
        type: array
      exception:
        $ref: '#/$defs/Criteria'
      minKakera:
        default: 9223372036854775807
        title: Minkakera
        type: integer
      series:
        items:
          type: string
        title: Series
        type: array
      wish:
        default: false
        title: Wish
        type: boolean
    title: ClaimCriteria
    type: object
  Criteria:
    properties:
      character:
        items:
          type: string
        title: Character
        type: array
      minKakera:
        default: 9223372036854775807
        title: Minkakera
        type: integer
      series:
        items:
          type: string
        title: Series
        type: array
      wish:
        default: false
        title: Wish
        type: boolean
    title: Criteria
    type: object
  DiscordConfig:
    properties:
      channelId:
        title: Channelid
        type: integer
      mudaeBotId:
        title: Mudaebotid
        type: integer
      token:
        title: Token
        type: string
    required:
    - token
    - channelId
    - mudaeBotId
    title: DiscordConfig
    type: object
  KakeraReactConfig:
    properties:
      doNotReactToKakeraTypeIfKakeraPowerLessThan:
        additionalProperties:
          type: integer
        title: Donotreacttokakeratypeifkakerapowerlessthan
        type: object
      doNotReactToKakeraTypes:
        items:
          type: string
        title: Donotreacttokakeratypes
        type: array
    title: KakeraReactConfig
    type: object
  MudaeConfig:
    properties:
      claim:
        $ref: '#/$defs/ClaimConfig'
      kakeraReact:
        $ref: '#/$defs/KakeraReactConfig'
      roll:
        $ref: '#/$defs/RollConfig'
    required:
    - roll
    title: MudaeConfig
    type: object
  RollConfig:
    properties:
      command:
        enum:
        - $wg
        - $wa
        - $w
        title: Command
        type: string
      doNotRollWhenCannotClaim:
        title: Donotrollwhencannotclaim
        type: boolean
      doNotRollWhenCannotKakeraReact:
        title: Donotrollwhencannotkakerareact
        type: boolean
      rollResetMinuteOffset:
        title: Rollresetminuteoffset
        type: integer
    required:
    - command
    - doNotRollWhenCannotClaim
    - doNotRollWhenCannotKakeraReact
    - rollResetMinuteOffset
    title: RollConfig
    type: object
additionalProperties: false
properties:
  discord:
    $ref: '#/$defs/DiscordConfig'
  mudae:
    $ref: '#/$defs/MudaeConfig'
  name:
    title: Name
    type: string
  version:
    const: 1
    title: Version
    type: integer
required:
- name
- version
- discord
- mudae
title: Config
type: object
